"""add document to conversations

Revision ID: f04c8f21b733
Revises: b7527c34f6f9
Create Date: 2026-08-19 20:31:12.386709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04c8f21b733'
down_revision: Union[str, Sequence[str], None] = 'b7527c34f6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_conversations_document_id'), 'conversations', ['document_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_document_id'), table_name='conversations')
    op.drop_column('conversations', 'document_id')
    # ### end Alembic commands ###
